stages:
  data_split:
    cmd: python src/data/split_data.py
    deps:
      - data/raw_data/raw.csv
      - src/data/split_data.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize_data:
    cmd: python src/data/normalize_data.py
    deps:
      - src/data/normalize_data.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv

  grid_search:
    cmd: python src/models/grid_search.py
    deps:
      - src/models/grid_search.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/best_params.pkl

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - models/best_params.pkl
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/trained_model.pkl

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - models/trained_model.pkl
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
    outs:
      - data/processed/predictions.csv
      - metrics/scores.json